spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/fallback/order

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**

            - id: ticket-service
              uri: lb://ticket-service
              predicates:
                - Path=/api/tickets/**
          server:
            error:
              include-message: always