spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always