spring:
  kafka:
    properties:
      session.timeout.ms: 45000
      heartbeat.interval.ms: 3000
      max.poll.interval.ms: 300000

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5