spring:
  datasource:
    url: jdbc:postgresql://order-db:5433/order_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      auto-offset-reset: earliest

saga:
  events:
    order-created: order-events
    payment-processed: payment-events
    ticket-reserved: ticket-events
  timeout:
    seconds: 60
  compensation:
    retries: 3
    backoff-ms: 1000