spring:
  datasource:
    url: jdbc:postgresql://payment-db:5432/payment_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka:9092}
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
    listener:
      dead-letter-topic: payment-events.DLT
      auto-startup: true
      retry:
        max-attempts: 3
        backoff:
          initial-interval: 1000ms
          multiplier: 2.0

payment:
  commission:
    rate: ${COMMISSION_RATE:0.02}
  currencies:
    supported: ${SUPPORTED_CURRENCIES:USD,EUR,RUB}
  settlement:
    timeout-hours: 24
  retry:
    max-attempts: 3
    backoff-ms: 1000
  timeout:
    payment-processing-ms: 30000
    refund-processing-ms: 60000