spring:
  datasource:
    url: jdbc:postgresql://ticket-db:5432/ticket_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:5000}

ticket:
  reservation:
    expiry-minutes: ${RESERVATION_EXPIRY:30}
    max-per-user: ${MAX_TICKETS_PER_USER:5}
  refund:
    deadline-days: ${REFUND_DEADLINE:7}

tour:
  integration:
    url: ${TOUR_SERVICE_URL:http://tour-service:8085}
    timeout: ${TOUR_TIMEOUT:5000}
    cache-ttl: ${TOUR_CACHE_TTL:3600}